### PR TITLE
Create es.po

### PR DESCRIPTION
**Pull request by kimbalear**
create dhis-web-user-profile/es.po

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@kimbalear Thanks for this. I was unaware of this app actually, so thanks for bring it to my attention. 

I have now added it to the translation server and enabled Spanish translations [here](https://translate.dhis2.org/es/user-profile-app/translate/i18n/module/es.po#filter=incomplete&unit=822774)

There are still a number of strings to translate there. Do you think you could complete the translation and then I can merge with the source code?

**Comment by jason-p-pickering** [comment]
@kimbalear if you want to work with the PO file directly (and not the translation server) I have added it [here](https://github.com/dhis2/user-profile-app/blob/translations/i18n/module/es.po) You can fork from ther e if you would prefer to do it that way. Thanks again!

**Comment by kimbalear** [comment]
Thank you very much Jason

**Comment by kimbalear** [comment]
Once completed I will let you know

**Comment by jason-p-pickering** [comment]
@kimbalear I will close this pull request and merge it into the user profile app once its done if that is OK? Gracias!

**Pull request closed without merging**
